title: Gisung Lab
email: your-email@example.com
description: >-
  난 대학에서 배울거 정리할거임
baseurl: "" 
url: ""
twitter_username: jekyllrb
github_username: jekyll

# Build settings
plugins:
  - jekyll-feed

# ------------------------------
# Markdown / Rouge 하이라이트 설정
# ------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
